SELECT * FROM customer_db.customers;

## revenue genearated by male and females customers
select gender, SUM(purchase_amount) as revenue
FROM customers
group by gender;

## customers that used dicount but still spent more than average purchase amount
select customer_id, purchase_amount
from customers
where discount_applied='Yes' 
and purchase_amount>=(
	select avg(purchase_amount)
    from customers
);

## Top 5 products with highest avg review rating
select item_purchased, round(avg(review_rating),2) as 'Average Product rating'
from customers
group by item_purchased
order by avg(review_rating) desc
limit 5;

##Compare the average purchase amount between standard and express shipping
select shipping_type, round(avg(purchase_amount),2)
from customers
where shipping_type in ('Standard', 'Express')
group by shipping_type;

## Compare average spend and total revenue between Subscribers and non subscribers
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customers
group by subscription_status
order by total_revenue, avg_spend desc;

##Top 5 products with highest percentage of purchase after discounts
select item_purchased, round(sum(
	case
		when discount_applied='Yes' then 1
        else 0
	end)/count(*)*100,2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;
 
## customers segemented to new, returning, and loyal based on total no of their previous purchases
with customer_type as(
	select customer_id, previous_purchases,
    case
		when previous_purchases=1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'loyal'
    end as customer_segment
	from customers
)

select customer_segment, count(*) as "number of customers"
from customer_type 
group by customer_segment;

## Top 3 most purchased product within each category
with item_counts as(
	select category, item_purchased,
    count(customer_id) as total_orders,
    row_number() over(partition by category order by count(customer_id) desc) as item_rank
    from customers
    group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;

## Are repeat buyers(more than 5 purchases) also subsribers?
select subscription_status, count(customer_id) as repeat_buyers
from customers
where previous_purchases>5
group by subscription_status;

##Revenue generated by each age group
select age_group, sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc;